/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi_dir_prj;

public class Module_1 {
    public String getGreeting() {
        return "Hello world from module 1";
    }

    public static void main(String[] args) {
        System.out.println(new Module_1().getGreeting());
    }
}
