/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi_dir_prj;

public class Module_4 {
    public String getGreeting() {
        return "Hello world. from module 4";
    }

    public static void main(String[] args) {
        System.out.println(new Module_4().getGreeting());
    }
}
